MTDSA-18405: Parser-validator improvements - individuals-business-eops-api
hmrc/individuals-business-eops-api pull request #102
Opened 2023-08-18 13:27 UTC by GazalNebHMRC

2023-08-21 13:15 UTC, SamuelJacobsHMRC requested changes

2023-08-21 13:15 UTC, SamuelJacobsHMRC commented on test/mocks/MockAppConfig.scala
> +    def isApiDeprecated(version: Version): CallHandler[Boolean]  = (mockAppConfig.isApiDeprecated: Version => Boolean).expects(version)
this will also need removing

2023-08-21 13:15 UTC, SamuelJacobsHMRC commented on test/v2/controllers/validators/SubmitEndOfPeriodStatementValidatorFactorySpec.scala
> +      "an invalid start date before end date is supplied" in {
end date before start date rather than start date before end date

2023-08-22 08:02 UTC, GazalNebHMRC commented on project/AppDependencies.scala
> +    "com.neovisionaries"            % "nv-i18n"                   % "1.29",
yes, it's being used in ResolveParsedCountryCode

2023-08-22 09:15 UTC, SamuelJacobsHMRC approved these changes

2023-08-22 09:15 UTC, merged